theme: just-the-docs
markdown: kramdown
plugins:
  - jekyll-toc

# Indique que les pages sont dans /docs
source: docs

# Optionnel : pour activer la TOC latérale du thème
just_the_docs:
  show_toc: true
  toc_levels: 1..3
