# --- Theme Configuration ---
remote_theme: "just-the-docs/just-the-docs"

# --- Site Information (Required) ---
title: Tutorial process raw Images with Darktable 5.x
description: A clean, documentation-focused Jekyll theme.

# --- JTD Sidebar Configuration ---
# The sidebar is the *main* left-side navigation structure.
# To hide the file extensions (e.g., .html), set this to true
aux_links_active: false

# --- JTD Table of Contents (Right Sidebar) ---
# This is the feature you are looking for!
# By default, Just the Docs *automatically* generates the sticky, right-side TOC
# based on your H2 and H3 headings when the page layout is set to 'default'.
